spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # Set your OpenAI API key in environment variable
      
  application:
    name: spring-ai

  redis:
    host: localhost    # Change to your Redis host
    port: 6379         # Default Redis port
